# Generated by Django 6.0.1 on 2026-02-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_favoriteclub_follow'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='no_self_follow'),
        ),
    ]
