# Generated by Django 6.0.1 on 2026-02-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_rating_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.URLField(blank=True, default=''),
        ),
    ]
