# Generated by Django 6.0.1 on 2026-04-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_matchplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lineup_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
