# Generated by Django 6.0.1 on 2026-04-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_add_lineup_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='positiion',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
