# Generated by Django 6.0.1 on 2026-04-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_matchplayer_is_starter_matchplayer_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchplayer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='matchplayer',
            name='positiion',
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
