# Generated by Django 6.0.1 on 2026-04-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_remove_matchplayer_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
