# Generated by Django 6.0.1 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='assists',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='subbed_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='subbed_out',
            field=models.BooleanField(default=False),
        ),
    ]
