# Generated by Django 6.0.1 on 2026-05-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_team_canonical_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status_display',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
