# Generated by Django 6.0.1 on 2026-05-31

import django.db.models.deletion
from django.db import migrations, models


def copy_player_team(apps, schema_editor):
    MatchPlayer = apps.get_model('matches', 'MatchPlayer')

    for match_player in MatchPlayer.objects.select_related('player').filter(team__isnull=True):
        match_player.team_id = match_player.player.team_id
        match_player.save(update_fields=['team'])


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_commentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='team',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='match_players',
                to='matches.team',
            ),
        ),
        migrations.RunPython(copy_player_team, migrations.RunPython.noop),
    ]
