# Generated by Django 6.0.1 on 2026-06-14 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_matchplayer_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commentreport',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matches.rating'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='matches.comment'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', False), ('rating__isnull', True)), models.Q(('comment__isnull', True), ('rating__isnull', False)), _connector='OR'), name='report_comment_or_rating'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('comment', 'reported_by'), name='unique_comment_report_by_user'),
        ),
        migrations.AddConstraint(
            model_name='commentreport',
            constraint=models.UniqueConstraint(fields=('rating', 'reported_by'), name='unique_rating_report_by_user'),
        ),
    ]
