# Generated by Django 6.0.1 on 2026-06-16 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_alter_commentreport_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='minute',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
