# Generated by Django 6.0.1 on 2026-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0020_match_minute'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='own_goals',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
